name: 'Install Dependencies'
description: 'Install dependencies for the pipeline'
runs:
  using: 'composite'
  steps:
    - name: Cache envs
      id: cache-envs
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.NXF_WORK }}/conda
          ${{ env.CONDA }}/envs
        key: env-${{ env.NXF_VER }}-${{ github.job }}
        restore-keys: |
          env-${{ env.NXF_VER }}-${{ github.job }}
          env-${{ env.NXF_VER }}
          env-
    - uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        download-micromamba: false
        micromamba-binary-path: /storage/gh-actions-alab/actions-runner/micromamba-bin
    - name: Setup nextflow
      uses: nf-core/setup-nextflow@v2
      with:
        version: ${{ env.NXF_VER }}
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'
      