name: freyja-sc2
channels:
    - bioconda
    - conda-forge
dependencies:
  - bioconda::cutadapt=5.0
  - bioconda::freyja=2.0.3
  - bioconda::minimap2
  - bioconda::sra-tools
  - conda-forge::pigz=2.8  
  - conda-forge::python=3.11
  - conda-forge::pyarrow
  - pip
  - pip:
    - epiweeks
    - pandas
    - frozendict
    - git+https://github.com/outbreak-info/python-outbreak-info
