name: freyja-sra
channels:
    - bioconda
    - conda-forge
dependencies:
  - bioconda::cutadapt=5.0
  - bioconda::freyja=1.5.3
  - bioconda::minimap2=2.26
  - bioconda::sra-tools=3.2.0
  - conda-forge::pigz=2.8  
  - conda-forge::python=3.10
  - conda-forge::pyarrow
  - conda-forge::google-cloud-sdk=458.0.1
  - pip
  - pip:
    - epiweeks
    - pandas
