name: freyja-sra
channels:
    - bioconda
    - conda-forge
dependencies:
  - bioconda::cutadapt=4.4
  - bioconda::freyja=1.5.1
  - bioconda::minimap2=2.26
  - conda-forge::python=3.11
  - conda-forge::awscli
  - conda-forge::pyarrow
  - conda-forge::google-cloud-sdk=458.0.1
  - conda-forge::procps-ng=3.3.17
  - hcc::aspera-cli
  - pip:
    - ffq
    - epiweeks
    - pandas
    - biopython
