name: Update NCBI metadata

on:
#   schedule:
#       - cron:  '0 0 */7 * *'
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  fetch_ncbi_metadata:
    runs-on: self-hosted


    steps:
      - name: fix permissions
        run: chmod -R u+rwX .
        
      - uses: actions/checkout@v4
        with: 
          path: ${{ github.sha }}

      - name: Setup for conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          environment-file: environment.yml
          mamba-version: "*"
          channels: conda-forge,bioconda
          conda-remove-defaults: "true"
          miniforge-version: latest
          channel-priority: true

      - name: Fetch NCBI metadata
        run: python scripts/fetch_sra_metadata.py

      - name: 'Get updated barcodes and lineages from Freyja repo'
        run: |
              git clone http://github.com/andersen-lab/Freyja
              cp Freyja/freyja/data/usher_barcodes.feather data/
              cp Freyja/freyja/data/lineages.yml data/
              cp Freyja/freyja/data/last_barcode_update.txt data/

      - name: 'Commit and push changes'
        run: |
              git config --local user.name "$GITHUB_ACTOR"
              git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
              git remote set-url origin https://github.com/andersen-lab/Freyja-SRA
              if [[($(git status data/usher_barcodes.feather --porcelain | wc -c) -ne 0)]]; then
                git add data/usher_barcodes.feather
                git add data/lineages.yml
                git add data/last_barcode_update.txt
              fi
              git add data/all_metadata.csv
              git commit -m "Update metadata"
              git push --force