name: Update NCBI metadata

on:
  push:
    branches:
      - main
  schedule:
      - cron: "0 0 * * *"

jobs:
  fetch_ncbi_metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup nextflow
        uses: nf-core/setup-nextflow@v1

      - name: Install dependencies
        run: |
              pip install pandas biopython shortuuid

      - name: Fetch NCBI metadata
        run: python scripts/fetch_sra_metadata.py

      - name: Run pipeline on new samples
        run: python scripts/run_new_samples.py

              
      


