name: fetch_ncbi_metadata

on:
  schedule:
      - cron: "0 0 * * *"

jobs:
  fetch_ncbi_metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Fetch NCBI metadata
        run: python fetch_ncbi_metadata.py
