name: Update NCBI metadata

on:
  schedule:
      - cron: "0 0 * * *"

jobs:
  fetch_ncbi_metadata:
    runs-on: ubuntu-latest
    container: dylanpilz/freyja-sra:latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch NCBI metadata
        run: python scripts/fetch_sra_metadata.py

      - name: Find new samples
        run: python scripts/find_new_samples.py

      - name: Run pipeline on new samples
        run: |
              nextflow run main.nf \
              --input samples_to_process.csv \
              -profile docker \
              -entry fetch_sra \
              -resume 
      - name: Commit and push changes (if any)
        run: 

