name: Update NCBI metadata

on:
  schedule:
      - cron:  '0/15 * * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  fetch_ncbi_metadata:
    runs-on: self-hosted

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Install python
        run: |
              echo ${{secrets.DPILZ_USR_PWD}} | sudo -S dnf install python3 -y
              echo ${{secrets.DPILZ_USR_PWD}} | sudo -S dnf install python3-pip -y

      - name: Install dependencies
        run: |
              pip install pandas biopython

      - name: Fetch NCBI metadata
        run: python scripts/fetch_sra_metadata.py

      - name: 'Commit and push changes'
        run: |
              git config --local user.name "$GITHUB_ACTOR"
              git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
              git remote set-url origin https://github.com/andersen-lab/Freyja-SRA
              git add data/all_metadata.csv
              git commit -m "Fetch NCBI metadata"
              git push --force