name: Process Samples

on:
  schedule:
    - cron: '0 */1 * * SAT'
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}

env:
  NXF_VER: "24.10.4"
  NXF_WORK: ${{ github.workspace }}/work
  NXF_OUTPUT: ${{ github.workspace }}/outputs
  NXF_NAME: github-${{ github.run_number }}
  TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_TOKEN }}
  TOWER_WORKSPACE_ID: ${{ secrets.TOWER_WORKSPACE_ID }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BATCH_SIZE: 125


defaults:
  run:
    shell: bash -eli {0}

jobs:
  run:
    runs-on: [self-hosted, profchaos]
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Cache envs
        id: cache-envs
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.NXF_WORK }}/conda
            $CONDA_PREFIX/envs
          key: env-${{ env.NXF_VER }}-${{ github.job }}
          restore-keys: |
            env-${{ env.NXF_VER }}-${{ github.job }}
            env-${{ env.NXF_VER }}
            env-

      - name: 'Check and setup conda environment'
        run: | 
          mamba env update --name freyja-sc2 --file environment.yml --prune

      - name: Run pipeline on new samples
        run: |
                mamba activate freyja-sc2
                nextflow run main.nf \
                  --num_samples $BATCH_SIZE \
                  -profile local \
                  -entry fetch

      - name: 'Update processed samples'
        if: ${{ hashFiles('data/accession_list.txt') != '' }}
        run: |
              mamba activate freyja-sc2
              python scripts/update_sample_status.py $BATCH_SIZE
          
      - name: Aggregate outputs
        if: ${{ hashFiles('data/accession_list.txt') != '' }}
        run: |
              mamba activate freyja-sc2
              python scripts/aggregate_variants.py
              python scripts/aggregate_metadata.py
      
      - name: 'Commit and push changes'
        if: ${{ hashFiles('data/accession_list.txt') != '' }}
        run: |
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              git config --global user.name "github-actions[bot]"
              git remote set-url origin https://github.com/andersen-lab/freyja-sc2
              git add data/all_metadata.tsv
              git commit -m "Update processed samples"
              git push

      - name: 'Create GitHub Run Summary'
        if: ${{ hashFiles('data/accession_list.txt') != '' }}
        run: |
          echo "# Job Summary $(date)" >> $GITHUB_STEP_SUMMARY
          echo "## Job Information" >> $GITHUB_STEP_SUMMARY
          cat data/all_metadata.tsv | rev | cut -f 2 | rev | sort | uniq -c >> $GITHUB_STEP_SUMMARY

      - name: 'Clean workspace'
        if: always()
        run: |
              rm -rf ${{ github.workspace }}/*
