name: Process samples

on:
  push:
    branches:
      - gcloud

jobs:
  run_samples:
    permissions:
      contents: read
      id-token: write

    runs-on: self-hosted

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup nextflow
        uses: nf-core/setup-nextflow@v1

      - name: Run pipeline on new samples
        run: |
              BATCH_SIZE=50

              nextflow run main.nf \
                  --accession_list data/samples_to_run.csv \
                  --num_samples $BATCH_SIZE \
                  -profile docker \
                  -entry sra &
              BACK_PID=$!
              wait $BACK_PID

              rm -rf work
              sed -i '2,51d' data/samples_to_run.csv

      - id: 'auth'
        name: 'Authenticate with gcloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/12767718289/locations/global/workloadIdentityPools/github/providers/freyja-sra'
          service_account: 'outbreak-ww@andersen-lab-primary.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
      
      - id: 'upload-outputs'
        name: 'Upload Outputs to Cloud Storage'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'outputs/*'
          destination: 'outbreak-ww/'
          parent: false

      - id: 'compose-aggregated-outputs'
        name: 'Concatenate aggregated outputs'
        run: |
              gcloud storage compose gs://outbreak-ww/aggregate/aggregate_demix.json gs://outbreak-ww/outputs/aggregate/aggregate_demix_new.json gs://outbreak-ww/outputs/aggregate/aggregate_demix.json
