name: Rerun demix
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}

env:
  NXF_VER: "24.10.4"
  NXF_WORK: ${{ github.workspace }}/work
  NXF_OUTPUT: ${{ github.workspace }}/outputs
  NXF_NAME: github-${{ github.run_number }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BATCH_SIZE: 100

defaults:
  run:  
    shell: bash -eli {0}
jobs:
  rerun_demix:
    runs-on: [self-hosted, profchaos]
    permissions:
        contents: write
        id-token: write

    steps:
      - name: Checkout main
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache envs
        id: cache-envs
        uses: actions/cache@v5
        with:
          path: |
            ${{ env.NXF_WORK }}/conda
            $CONDA_PREFIX/envs
          key: env-${{ env.NXF_VER }}-${{ github.job }}
          restore-keys: |
            env-${{ env.NXF_VER }}-${{ github.job }}
            env-${{ env.NXF_VER }}
            env-

      - name: 'Check and setup conda environment'
        run: | 
          mamba env update --name freyja-sc2 --file environment.yml --prune
          
      - name: 'Get samples to re-run'
        run: |
              mkdir demix_rerun
              mamba activate freyja-sc2
              python scripts/get_samples_for_demix_rerun.py
              
      - name: 'Get variants output'
        run: |
              mamba activate freyja-sc2
              bash scripts/get_variants_output.sh
      
      - name: 'Rerun demix'
        run: |
              mamba activate freyja-sc2
              export NXF_ENABLE_VIRTUAL_THREADS=false
              nextflow run main.nf \
                -entry rerun_demix \
                -profile local \
                --accession_list data/samples_to_rerun.csv \
                --variants_dir demix_rerun


